name: Deploy Theme via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Hostnin Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Exclude git and workflow files from being uploaded
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
        # The path on your server where the theme should be uploaded.
        # If your FTP drops you in the root of your hosting, it's usually:
        # public_html/wp-content/themes/raisul-sohan/
        server-dir: public_html/wp-content/themes/raisul-sohan/
